/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./application/views/**/*.php", "./assets/script/**/*.js"],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          "LINE Seed EN",
          "LINE Seed EN Bold",
          "LINE Seed TH",
          "LINE Seed TH Bold",
          "LINE Seed JP",
          "LINE Seed JP Bold",
          "sans-serif",
        ],
      },
      colors: {
        cOrange: "#e38300",
        primary: "#e38300",
        active: "#c06f01",
        accent: "#007fe3",
        accentActive: "#0069bc",
        background: "#fefdfb",
        text: "#2b1900",
        running :'#0000FF',
        reject:'#FF0000',
        approve:'#009900'
      },
      keyframes: {
        moveSide: {
          "0%, 100%": { transform: "translateX(0)" },
          "50%": { transform: "translateX(20px)" },
        },
        smoke: {
          "0%": { transform: "scale(0.5)", opacity: "1" },
          "100%": { transform: "scale(2)", opacity: "0" },
        },
      },
      animation: {
        moveSide: "moveSide 1s ease-in-out infinite",
        smoke: "smoke 2s ease-in-out infinite",
      },
    },
  },
  daisyui: {
    themes: [
      {
        light: {
            ...require("daisyui/src/theming/themes")["light"],
            primary: "#e38300",
            secondary: "#8a8a8b",
            accent: "#007fe3",
            neutral: "#020017",
            info: "#00b7eb",
            success: "#29ab87",
            warning: "#ffbf00",
            error: "#f55959",
            "base-100": "#ffffff",
            "primary-content": "#feefd9",
            "neutral-content": "#FFFFFF",
            "accent-content": "#FFFFFF",
            "error-content": "#FFFFFF",
            "success-content": "#FFFFFF",
        },
      },
      // "light",
    //   "dark",
    //   "cupcake",
    //   "bumblebee",
    //   "emerald",
    //   "corporate",
    //   "synthwave",
    //   "retro",
    //   "cyberpunk",
    //   "valentine",
    //   "halloween",
    //   "garden",
    //   "forest",
    //   "aqua",
    //   "lofi",
    //   "pastel",
    //   "fantasy",
    //   "wireframe",
    //   "black",
    //   "luxury",
    //   "dracula",
    //   "cmyk",
    //   "autumn",
    //   "business",
    //   "acid",
    //   "lemonade",
    //   "night",
    //   "coffee",
    //   "winter",
    //   "dim",
    //   "nord",
    //   "sunset",
    ],
  },
  plugins: [require("daisyui")],
  
};
